
name: Scan for secrets

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.18'
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: TruffleHog
      uses: ./
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD